version: '3'
services:
  db:
    # SQL Server 2019 でビルド
    image: mcr.microsoft.com/mssql/server:2019-latest

    # ポート設定
    ports:
      - 1433:1433

    # 環境変数を設定
    environment:
      MSSQL_PID: Express # ライセンスが不要な Express エディションを使用する
      ACCEPT_EULA: Y # EULA（使用許諾契約）に同意する ※これを入れないと起動できない
      TZ: Asia/Tokyo # タイムゾーンを JST で設定
      SA_PASSWORD: Test1234 # パスワード
      MSSQL_AGENT_ENABLED: 'true' # SQLServer を落とさずに起動し続ける
      PATH: $PATH:/opt/mssql-tools/bin/ #sqlcmd の PATH を通す

    # ホスト側ディレクトリとコンテナをマウント
    # この docker-compose.yml と同じ階層の mount_dir ディレクトリ配下にファイルを配置すると、コンテナ上の root 配下にある同名ディレクトリへ同期される
    volumes:
      - ./mount_dir:/mount_dir
